# Generated by Django 3.2.7 on 2021-12-02 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20211127_0758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='castomer',
        ),
    ]
