# Generated by Django 3.2.7 on 2021-12-02 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_user_order_castomer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='castomer',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.customer'),
        ),
    ]
