# Generated by Django 3.2.7 on 2021-09-22 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210918_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Наименование')),
                ('description', models.TextField(max_length=256, verbose_name='Описание')),
                ('slug', models.SlugField(default='test', max_length=32, unique=True)),
            ],
            options={
                'verbose_name': 'Группа модификаторов',
                'verbose_name_plural': 'Группы модификаторов',
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_vegan',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='test', max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_vegan',
            field=models.BooleanField(default=False, verbose_name='Вегатарианска?'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='test', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category', verbose_name='категория'),
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Наименование')),
                ('description', models.TextField(max_length=256, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('is_vegan', models.BooleanField(verbose_name='Вегатарианска?')),
                ('slug', models.SlugField(default='test', max_length=32, unique=True)),
                ('modifier_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.modifiergroup', verbose_name='Группа модификаторов')),
            ],
            options={
                'verbose_name': 'Модификатор',
                'verbose_name_plural': 'Модификаторы',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='modifier_groups',
            field=models.ManyToManyField(blank=True, to='catalog.ModifierGroup'),
        ),
    ]
