# Generated by Django 3.2.7 on 2021-11-30 09:52

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20211130_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cart_image',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_image', models.ImageField(blank=True, null=True, upload_to='static/img', validators=[catalog.validators.image_resolution_check_cart], verbose_name='Изображение для таблицы')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
        ),
    ]
